local areaDefaultStartRooms = {
    ["abend"] = {start = "24909", ct = "3"}, -- Continents
    ["alagh"] = {start = "3224", ct = "4"},
    ["gelidus"] = {start = "18780", ct = "2"},
    ["mesolar"] = {start = "12664", ct = "0"},
    ["southern"] = {start = "5192", ct = "1"},
    ["uncharted"] = {start = "7701", ct = "5"},
    ["vidblain"] = {start = "33570", ct = "6", vidblain = true},
    ["aardington"] = {start = "47509"}, -- A --
    ["academy"] = {start = "35233"},
    ["adaldar"] = {start = "34400"},
    ["afterglow"] = {start = "38134"},
    ["agroth"] = {start = "11027"},
    ["ahner"] = {start = "30129"},
    ["alehouse"] = {start = "885"},
    ["amazon"] = {start = "1409"},
    ["amusement"] = {start = "29282"},
    ["andarin"] = {start = "2399"},
    ["annwn"] = {start = "28963"},
    ["anthrox"] = {start = "3993"},
    ["arboretum"] = {start = "39100"},
    ["arena"] = {start = "25768"},
    ["arisian"] = {start = "28144"},
    ["ascent"] = {start = "43150"},
    ["asherodan"] = {start = "37400", vidblain = true},
    ["astral"] = {start = "27882"},
    ["atlantis"] = {start = "10573"},
    ["autumn"] = {start = "13839"},
    ["avian"] = {start = "4334"},
    ["aylor"] = {start = "32418"},
    ["bazaar"] = {start = "34454"}, -- B --
    ["beer"] = {start = "20062"},
    ["believer"] = {start = "25940"},
    ["blackrose"] = {start = "1817"},
    ["bliss"] = {start = "29988"},
    ["bonds"] = {start = "23411"},
    ["caldera"] = {start = "26341"}, -- C --
    ["callhero"] = {start = "33031"},
    ["camps"] = {start = "4714"},
    ["canyon"] = {start = "25551"},
    ["caravan"] = {start = "16071"},
    ["cards"] = {start = "6255"},
    ["carnivale"] = {start = "28635"},
    ["cataclysm"] = {start = "19976"},
    ["cathedral"] = {start = "27497"},
    ["cats"] = {start = "40900"},
    ["chasm"] = {start = "29446"},
    ["chakra"] = {start = "0"},
    ["chantry"] = {start = "0"},
    ["chessboard"] = {start = "25513"},
    ["childsplay"] = {start = "678"},
    ["cineko"] = {start = "1507"},
    ["citadel"] = {start = "14963"},
    ["conflict"] = {start = "27711"},
    ["coral"] = {start = "4565"},
    ["cougarian"] = {start = "14311"},
    ["cove"] = {start = "49941"},
    ["cradle"] = {start = "11267"},
    ["crynn"] = {start = "43800"},
    ["damned"] = {start = "10469"}, -- D --
    ["darklight"] = {start = "19642", vidblain = true},
    ["darkside"] = {start = "15060"},
    ["ddoom"] = {start = "4193"},
    ["deadlights"] = {start = "16856"},
    ["deathtrap"] = {start = "1767"},
    ["deneria"] = {start = "35006"},
    ["desert"] = {start = "20186"},
    ["desolation"] = {start = "19532"},
    ["dhalgora"] = {start = "16755"},
    ["diatz"] = {start = "1254"},
    ["diner"] = {start = "36700"},
    ["dortmund"] = {start = "16577"},
    ["drageran"] = {start = "25894"},
    ["dread"] = {start = "26075"},
    ["dsr"] = {start = "30030"},
    ["dundoom"] = {start = "25661"},
    ["dunes"] = {start = "42170"},
    ["dunoir"] = {start = "14222"},
    ["duskvalley"] = {start = "37301"},
    ["dynasty"] = {start = "30799"},
    ["earthlords"] = {start = "42000"}, -- E --
    ["earthplane"] = {start = "1354"},
    ["elemental"] = {start = "41624"},
    ["empire"] = {start = "32203"},
    ["empyrean"] = {start = "14042"},
    ["entropy"] = {start = "29773"},
    ["fantasy"] = {start = "15205"}, -- F --
    ["farm"] = {start = "10676"},
    ["fayke"] = {start = "30418"},
    ["fens"] = {start = "16528"},
    ["fields"] = {start = "29232"},
    ["firebird"] = {start = "32885"},
    ["firenation"] = {start = "41879"},
    ["fireswamp"] = {start = "34755"},
    ["fortress"] = {start = "31835"},
    ["fortune"] = {start = "38561"},
    ["fractured"] = {start = "17033"},
    ["ft1"] = {start = "1205"},
    ["ftii"] = {start = "26673"},
    ["gallows"] = {start = "4344"}, -- G --
    ["gathering"] = {start = "36451"},
    ["gauntlet"] = {start = "31652"},
    ["gilda"] = {start = "4243"},
    ["glamdursil"] = {start = "35055"},
    ["glimmerdim"] = {start = "26252"},
    ["gnomalin"] = {start = "34397"},
    ["goldrush"] = {start = "15014"},
    ["graveyard"] = {start = "28918"},
    ["greece"] = {start = "2089"},
    ["gwillim"] = {start = "25974"},
    ["hades"] = {start = "29161"}, -- H --
    ["hatchling"] = {start = "34670"},
    ["hawklord"] = {start = "40550"},
    ["hedge"] = {start = "15146"},
    ["helegear"] = {start = "30699"},
    ["hell"] = {start = "30984"},
    ["hoard"] = {start = "1675"},
    ["hodgepodge"] = {start = "30469"},
    ["horath"] = {start = "91"},
    ["horizon"] = {start = "31959"},
    ["illoria"] = {start = "10420"},
    ["imagi"] = {start = "36800"}, -- I --
    ["imperial"] = {start = "16966", vidblain = true},
    ["infamy"] = {start = "26641"},
    ["infest"] = {start = "16165"},
    ["insan"] = {start = "6850"},
    ["jenny"] = {start = "29637"}, -- J --
    ["jotun"] = {start = "31508"},
    ["kearvek"] = {start = "29722"}, -- K --
    ["kerofk"] = {start = "16405"},
    ["ketu"] = {start = "35114"},
    ["kingsholm"] = {start = "27522"},
    ["knossos"] = {start = "28193"},
    ["kobaloi"] = {start = "10691"},
    ["kultiras"] = {start = "31161"},
    ["lab"] = {start = "28684"}, -- L --
    ["labyrinth"] = {start = "31405"},
    ["lagoon"] = {start = "30549"},
    ["landofoz"] = {start = "510"},
    ["laym"] = {start = "6005"},
    ["legend"] = {start = "16224"},
    ["lemdagor"] = {start = "1966"},
    ["lidnesh"] = {start = "27995"},
    ["livingmine"] = {start = "37008"},
    ["logging"] = {start = "31254"},
    ["longnight"] = {start = "26367"},
    ["losttime"] = {start = "28584"},
    ["lowlands"] = {start = "28044"},
    ["lplanes"] = {start = "29364"},
    ["maelstrom"] = {start = "38058"}, -- M --
    ["manor"] = {start = "10621"},
    ["masq"] = {start = "29840"},
    ["mayhem"] = {start = "1866"},
    ["melody"] = {start = "14172"},
    ["minos"] = {start = "20472"},
    ["mistridge"] = {start = "4491"},
    ["monastery"] = {start = "15756"},
    ["mudwog"] = {start = "2347"},
    ["nanjiki"] = {start = "11203"}, -- N --
    ["necro"] = {start = "29922"},
    ["nenukon"] = {start = "31784"},
    ["newthalos"] = {start = "23853"},
    ["ninehells"] = {start = "4613"},
    ["northstar"] = {start = "11127"},
    ["nottingham"] = {start = "11077"},
    ["nulan"] = {start = "37900"},
    ["nursing"] = {start = "31977"},
    ["nynewoods"] = {start = "23562"},
    ["oceanpark"] = {start = "39600"}, -- O --
    ["omentor"] = {start = "15579", vidblain = true},
    ["ooku"] = {start = "39000"},
    ["origins"] = {start = "35900"},
    ["orlando"] = {start = "30331"},
    ["paradise"] = {start = "29624"}, -- P --
    ["partroxis"] = {start = "5814"},
    ["peninsula"] = {start = "35701"},
    ["petstore"] = {start = "995"},
    ["pompeii"] = {start = "57"},
    ["promises"] = {start = "25819"},
    ["prosper"] = {start = "28268"},
    ["qong"] = {start = "16115"}, -- Q --
    ["quarry"] = {start = "23510"},
    ["radiance"] = {start = "19805"}, -- R --
    ["raga"] = {start = "19861"},
    ["raukora"] = {start = "6040"},
    ["rebellion"] = {start = "10305"},
    ["remcon"] = {start = "25837"},
    ["reme"] = {start = "32703"},
    ["rosewood"] = {start = "6901"},
    ["ruins"] = {start = "16805"},
    ["sagewood"] = {start = "28754"}, -- S --
    ["sahuagin"] = {start = "34592"},
    ["salt"] = {start = "4538"},
    ["sanctity"] = {start = "10518"},
    ["sanctum"] = {start = "15307"},
    ["sandcastle"] = {start = "37701"},
    ["sanguine"] = {start = "15436"},
    ["scarred"] = {start = "34036"},
    ["sendhian"] = {start = "20288", vidblain = true},
    ["sennarre"] = {start = "15491"},
    ["shadowsend"] = {start = "40096"},
    ["shouggoth"] = {start = "34087"},
    ["siege"] = {start = "43265"},
    ["sirens"] = {start = "16298"},
    ["slaughter"] = {start = "1601"},
    ["snuckles"] = {start = "182"},
    ["soh"] = {start = "25611"},
    ["sohtwo"] = {start = "30752"},
    ["solan"] = {start = "23713"},
    ["songpalace"] = {start = "47013"},
    ["spyreknow"] = {start = "34800"},
    ["stone"] = {start = "11386"},
    ["storm"] = {start = "6304"},
    ["stormhaven"] = {start = "20649"},
    ["stronghold"] = {start = "20572"},
    ["stuff"] = {start = "40400"},
    ["takeda"] = {start = "15952"}, -- T --
    ["talsa"] = {start = "26917"},
    ["temple"] = {start = "31597"},
    ["tanra"] = {start = "46913"},
    ["terra"] = {start = "19679"},
    ["terramire"] = {start = "4493"},
    ["thieves"] = {start = "7"},
    ["tilule"] = {start = "39771"},
    ["times"] = {start = "28463"},
    ["tirna"] = {start = "20136"},
    ["titan"] = {start = "38234"},
    ["tol"] = {start = "16325"},
    ["tombs"] = {start = "15385"},
    ["umari"] = {start = "36601"}, -- U --
    ["underdark"] = {start = "27341"},
    ["uplanes"] = {start = "29364"},
    ["uprising"] = {start = "15382"},
    ["vale"] = {start = "1036"}, -- V --
    ["verdure"] = {start = "24090"},
    ["verume"] = {start = "30607"},
    ["village"] = {start = "30850"},
    ["vlad"] = {start = "15970"},
    ["volcano"] = {start = "6091"},
    ["weather"] = {start = "40499"}, -- W --
    ["werewood"] = {start = "30956"},
    ["wildwood"] = {start = "322"},
    ["winter"] = {start = "1306"},
    ["wizards"] = {start = "31316"},
    ["wonders"] = {start = "32981"},
    ["wooble"] = {start = "11335"},
    ["woodelves"] = {start = "32199"},
    ["wtc"] = {start = "37895"},
    ["wyrm"] = {start = "28847"},
    ["xmas"] = {start = "6212"}, -- X --
    ["xylmos"] = {start = "472"},
    ["yarr"] = {start = "30281"},
    ["ygg"] = {start = "24186"}, -- Y --
    ["yurgach"] = {start = "29450"},
    ["zangar"] = {start = "6164"}, -- Z --
    ["zenith"] = {start = "23681"},
    ["zodiac"] = {start = "15857"},
    ["zoo"] = {start = "5920"},
    ["zyian"] = {start = "729"},
    -- Non-questable Areas
    ["manor1"] = {start = "14460", noquest = true}, -- Manor areas
    ["manor3"] = {start = "20836", noquest = true},
    ["manorisle"] = {start = "6366", noquest = true},
    ["manormount"] = {start = "39449", noquest = true},
    ["manorsea"] = {start = "35003", noquest = true},
    ["manorville"] = {start = "35004", noquest = true},
    ["manorwoods"] = {start = "35002", noquest = true},
    ["blackclaw"] = {start = "   -1", noquest = true}, -- epic areas
    ["geniewish"] = {start = "38464", noquest = true},
    ["icefall"] = {start = "38701", noquest = true},
    ["inferno"] = {start = "-1", noquest = true},
    ["oradrin"] = {start = "25436", noquest = true},
    ["transcend"] = {start = "0", noquest = true},
    ["winds"] = {start = "39900", noquest = true},
    ["badtrip"] = {start = "32877", noquest = true}, -- Other no-quest areas
    ["birthday"] = {start = "10920", noquest = true},
    ["seaking"] = {start = "-1", noquest = true},
    ["amazonclan"] = {start = "34212", noquest = true}, -- Public clan halls
    ["bard"] = {start = "30538", noquest = true},
    ["bootcamp"] = {start = "49256", noquest = true},
    ["cabal"] = {start = "15704", noquest = true},
    ["chaos"] = {start = "28909", noquest = true},
    ["crimson"] = {start = "27989", noquest = true},
    ["crusaders"] = {start = "31122", noquest = true},
    ["daoine"] = {start = "30949", noquest = true},
    ["doh"] = {start = "16803", noquest = true},
    ["dominion"] = {start = "5863", noquest = true},
    ["dragon"] = {start = "642", noquest = true},
    ["druid"] = {start = "29582", noquest = true},
    ["emerald"] = {start = "831", noquest = true},
    ["gaardian"] = {start = "20026", noquest = true},
    ["imperium"] = {start = "30415", noquest = true},
    ["light"] = {start = "2339", noquest = true},
    ["loqui"] = {start = "28580", noquest = true},
    ["masaki"] = {start = "15852", noquest = true},
    ["perdition"] = {start = "19968", noquest = true},
    ["pyre"] = {start = "15141", noquest = true},
    ["romani"] = {start = "24180", noquest = true},
    ["seekers"] = {start = "14165", noquest = true},
    ["shadokil"] = {start = "32407", noquest = true},
    ["tanelorn"] = {start = "31561", noquest = true},
    ["tao"] = {start = "29210", noquest = true},
    ["touchstone"] = {start = "28346", noquest = true},
    ["twinlobe"] = {start = "15575", noquest = true},
    ["vanir"] = {start = "878", noquest = true},
    ["watchmen"] = {start = "32342", noquest = true},
    ["baal"] = {start = "-1", noquest = true}, -- Closed clan halls
    ["hook"] = {start = "-1", noquest = true},
    ["retri"] = {start = "-1", noquest = true},
    ["rhabdo"] = {start = "-1", noquest = true},
    ["rogues"] = {start = "-1", noquest = true},
    ["xunti"] = {start = "-1", noquest = true},
    ["challenge"] = {start = "-1", noquest = true}, -- Normally inaccessible areas, or which lack a sensible starting room.
    ["immhomes"] = {start = "-1", noquest = true},
    ["lasertwo"] = {start = "-1", noquest = true},
    ["limbo"] = {start = "-1", noquest = true},
    ["lualand"] = {start = "-1", noquest = true},
    ["midgaard"] = {start = "-1", noquest = true},
    ["oldclanone"] = {start = "-1", noquest = true},
    ["oldclantwo"] = {start = "-1", noquest = true},
    ["oldclanthr"] = {start = "-1", noquest = true},
    ["oldclanfou"] = {start = "-1", noquest = true},
    ["vault"] = {start = "-1", noquest = true},
    ["warzone"] = {start = "-1", noquest = true},
    ["wolfmaze"] = {start = "-1", noquest = true}
}

local vidblain_area_list = {
    ["asherodan"] = {},
    ["darklight"] = {},
    ["imperial"] = {},
    ["omentor"] = {},
    ["sendhian"] = {},
    ["vidblain"] = {}
}

--	[[ Lookup table to get area id from area long name ]]
local areaNameXref = {
    ["A Genie's Last Wish"] = "geniewish",
    ["A Magical Hodgepodge"] = "hodgepodge",
    ["A Peaceful Giant Village"] = "village",
    ["Aardington Estate"] = "aardington",
    ["Aardwolf Zoological Park"] = "zoo",
    ["Adventures in Sendhia"] = "sendhian",
    ["Aerial City of Cineko"] = "cineko",
    ["Afterglow"] = "afterglow",
    ["Alagh, the Blood Lands"] = "alagh",
    ["All in a Fayke Day"] = "fayke",
    ["An Auspicious Star's Zenith"] = "zenith",
    ["Ancient Greece"] = "greece",
    ["Andolor's Ocean Adventure Park"] = "oceanpark",
    ["Annwn"] = "annwn",
    ["Anthrox"] = "anthrox",
    ["Arboretum"] = "arboretum",
    ["Arisian Realm"] = "arisian",
    ["Art of Melody"] = "melody",
    ["Artificer's Mayhem"] = "mayhem",
    ["Ascension Bluff Nursing Home"] = "nursing",
    ["Atlantis"] = "atlantis",
    ["Avian Kingdom"] = "avian",
    ["Battlefields of Adaldar"] = "adaldar",
    ["Black Lagoon"] = "lagoon",
    ["Black Rose"] = "blackrose",
    ["Brightsea and Glimmerdim"] = "glimmerdim",
    ["Canyon Memorial Hospital"] = "canyon",
    ["Castle Vlad-Shamir"] = "vlad",
    ["Chakra Spire"] = "chakra",
    ["Chaprenula's Laboratory"] = "lab",
    ["Child's Play"] = "childsplay",
    ["Christmas Vacation"] = "xmas",
    ["Cloud City of Gnomalin"] = "gnomalin",
    ["Cradlebrook"] = "cradle",
    ["Crossroads of Fortune"] = "fortune",
    ["Crynn's Church"] = "crynn",
    ["Dark Elf Stronghold"] = "stronghold",
    ["Death's Manor"] = "manor",
    ["Deathtrap Dungeon"] = "deathtrap",
    ["Den of Thieves"] = "thieves",
    ["Descent to Hell"] = "hell",
    ["Desert Doom"] = "ddoom",
    ["Dhal'Gora Outlands"] = "dhalgora",
    ["Diamond Soul Revelation"] = "dsr",
    ["Dortmund"] = "dortmund",
    ["Dread Tower"] = "dread",
    ["Dunes in Gold"] = "dunes",
    ["Dusk Valley"] = "duskvalley",
    ["Earth Plane 4"] = "earthplane",
    ["Elemental Chaos"] = "elemental",
    ["Empyrean, Streets of Downfall"] = "empyrean",
    ["Entrance to Hades"] = "hades",
    ["Eternal Autumn"] = "autumn",
    ["Faerie Tales II"] = "ftii",
    ["Faerie Tales"] = "ft1",
    ["Fantasy Fields"] = "fantasy",
    ["Fellchantry"] = "chantry",
    ["Foolish Promises"] = "promises",
    ["Fort Terramire"] = "terramire",
    ["Gallows Hill"] = "gallows",
    ["Gelidus"] = "gelidus",
    ["Giant's Pet Store"] = "petstore",
    ["Gilda And The Dragon"] = "gilda",
    ["Gnoll's Quarry"] = "quarry",
    ["Gold Rush"] = "goldrush",
    ["Guardian's Spyre of Knowledge"] = "spyreknow",
    ["Wayfarer's Caravan"] = "caravan",
    ["Halls of the Damned"] = "damned",
    ["Hatchling Aerie"] = "hatchling",
    ["Hedgehogs' Paradise"] = "hedge",
    ["Helegear Sea"] = "helegear",
    ["Hotel Orlando"] = "orlando",
    ["House of Cards"] = "cards",
    ["Icefall"] = "icefall",
    ["Imagi's Nation"] = "imagi",
    ["Imperial Nation"] = "imperial",
    ["Insanitaria"] = "insan",
    ["Into the Long Night"] = "longnight",
    ["Intrigues of Times Past"] = "times",
    ["Island of Lost Time"] = "losttime",
    ["Jenny's Tavern"] = "jenny",
    ["Jotunheim"] = "jotun",
    ["Jungles of Verume"] = "verume",
    ["Keep of the Kobaloi"] = "kobaloi",
    ["Kerofk"] = "kerofk",
    ["Ketu Uplands"] = "ketu",
    ["Kiksaadi Cove"] = "cove",
    ["Kimr's Farm"] = "farm",
    ["Kingdom of Ahner"] = "ahner",
    ["Kingsholm"] = "kingsholm",
    ["Kobold Siege Camp"] = "siege",
    ["Kul Tiras"] = "kultiras",
    ["Land of Legend"] = "legend",
    ["Living Mines of Dak'Tai"] = "livingmine",
    ["Masquerade Island"] = "masq",
    ["Mount duNoir"] = "dunoir",
    ["Mudwog's Swamp"] = "mudwog",
    ["Nanjiki Ruins"] = "nanjiki",
    ["Nebulous Horizon"] = "horizon",
    ["Necromancers' Guild"] = "necro",
    ["Nenukon and the Far Country"] = "nenukon",
    ["New Thalos"] = "newthalos",
    ["Northstar"] = "northstar",
    ["Nottingham"] = "nottingham",
    ["Olde Worlde Carnivale"] = "carnivale",
    ["Onyx Bazaar"] = "bazaar",
    ["Ookushka Garrison"] = "ooku",
    ["Paradise Lost"] = "paradise",
    ["Plains of Nulan'Boar"] = "nulan",
    ["Pompeii"] = "pompeii",
    ["Prosper's Island"] = "prosper",
    ["Qong"] = "qong",
    ["Radiance Woods"] = "radiance",
    ["Raganatittu"] = "raga",
    ["Realm of Deneria"] = "deneria",
    ["Realm of the Firebird"] = "firebird",
    ["Realm of the Sacred Flame"] = "firenation",
    ["Realm of the Zodiac"] = "zodiac",
    ["Rebellion of the Nix"] = "rebellion",
    ["Rosewood Castle"] = "rosewood",
    ["Sagewood Grove"] = "sagewood",
    ["Sanctity of Eternal Damnation"] = "sanctity",
    ["Sen'narre Lake"] = "sennarre",
    ["Seven Wonders"] = "wonders",
    ["Shadow's End"] = "shadowsend",
    ["Sheila's Cat Sanctuary"] = "cats",
    ["Sho'aram, Castle in the Sand"] = "sandcastle",
    ["Siren's Oasis Resort"] = "sirens",
    ["Snuckles Village"] = "snuckles",
    ["Storm Mountain"] = "storm",
    ["Storm Ships of Lem-Dagor"] = "lemdagor",
    ["Sundered Vale"] = "vale",
    ["Swordbreaker's Hoard"] = "hoard",
    ["Tairayden Peninsula"] = "peninsula",
    ["Tai'rha Laym"] = "laym",
    ["Takeda's Warcamp"] = "takeda",
    ["Tanra'vea"] = "tanra",
    ["Thandeld's Conflict"] = "conflict",
    ["The Abyssal Caverns of Sahuagin"] = "sahuagin",
    ["The Amazon Nation"] = "amazon",
    ["The Amusement Park"] = "amusement",
    ["The Archipelago of Entropy"] = "entropy",
    ["The Astral Travels"] = "astral",
    ["The Aylorian Academy"] = "academy",
    ["The Blighted Tundra of Andarin"] = "andarin",
    ["The Blood Opal of Rauko'ra"] = "raukora",
    ["The Blood Sanctum"] = "sanctum",
    ["The Broken Halls of Horath"] = "horath",
    ["The Call of Heroes"] = "callhero",
    ["The Cataclysm"] = "cataclysm",
    ["The Chasm and The Catacombs"] = "chasm",
    ["The Chessboard"] = "chessboard",
    ["The Continent of Mesolar"] = "mesolar",
    ["The Coral Kingdom"] = "coral",
    ["The Cougarian Queendom"] = "cougarian",
    ["The Council of the Wyrm"] = "wyrm",
    ["The Covenant of Mistridge"] = "mistridge",
    ["The Cracks of Terra"] = "terra",
    ["The Curse of the Midnight Fens"] = "fens",
    ["The Dark Continent, Abend"] = "abend",
    ["The Dark Temple of Zyian"] = "zyian",
    ["The DarkLight"] = "darklight",
    ["The Darkside of the Fractured Lands"] = "darkside",
    ["The Deadlights"] = "deadlights",
    ["The Desert Prison"] = "desert",
    ["The Drageran Empire"] = "drageran",
    ["The Dungeon of Doom"] = "dundoom",
    ["The Earth Lords"] = "earthlords",
    ["The Eighteenth Dynasty"] = "dynasty",
    ["The Empire of Aiighialla"] = "empire",
    ["The Empire of Talsa"] = "talsa",
    ["The Fabled City of Stone"] = "stone",
    ["The Fire Swamp"] = "fireswamp",
    ["The First Ascent"] = "ascent",
    ["The Flying Citadel"] = "citadel",
    ["The Forest of Li'Dnesh"] = "lidnesh",
    ["The Fractured Lands"] = "fractured",
    ["The Gathering Horde"] = "gathering",
    ["The Gauntlet"] = "gauntlet",
    ["The Gladiator's Arena"] = "arena",
    ["The Glamdursil"] = "glamdursil",
    ["The Goblin Fortress"] = "fortress",
    ["The Grand City of Aylor"] = "aylor",
    ["The Graveyard"] = "graveyard",
    ["The Great City of Knossos"] = "knossos",
    ["The Great Salt Flats"] = "salt",
    ["The Icy Caldera of Mauldoon"] = "caldera",
    ["The Imperial City of Reme"] = "reme",
    ["The Infestation"] = "infest",
    ["The Keep of Kearvek"] = "kearvek",
    ["The Killing Fields"] = "fields",
    ["The Labyrinth"] = "labyrinth",
    ["The Land of Oz"] = "landofoz",
    ["The Land of the Beer Goblins"] = "beer",
    ["The Lower Planes"] = "lplanes",
    ["The Maelstrom"] = "maelstrom",
    ["The Marshlands of Agroth"] = "agroth",
    ["The Misty Shores of Yarr"] = "yarr",
    ["The Monastery"] = "monastery",
    ["The Mountains of Desolation"] = "desolation",
    ["The Nine Hells"] = "ninehells",
    ["The Nyne Woods"] = "nynewoods",
    ["The Old Cathedral"] = "cathedral",
    ["The Palace of Song"] = "songpalace",
    ["The Partroxis"] = "partroxis",
    ["The Path of the Believer"] = "believer",
    ["The Realm of Infamy"] = "infamy",
    ["The Realm of the Hawklords"] = "hawklord",
    ["The Relinquished Tombs"] = "tombs",
    ["The Reman Conspiracy"] = "remcon",
    ["The Ruins of Diamond Reach"] = "ruins",
    ["The Ruins of Stormhaven"] = "stormhaven",
    ["The Sanguine Tavern"] = "sanguine",
    ["The Scarred Lands"] = "scarred",
    ["The School of Horror"] = "soh",
    ["The Shadows of Minos"] = "minos",
    ["The Silver Volcano"] = "volcano",
    ["The Slaughter House"] = "slaughter",
    ["The Southern Ocean"] = "southern",
    ["The Stuff of Shadows"] = "stuff",
    ["The Temple of Shal'indrael"] = "temple",
    ["The Temple of Shouggoth"] = "shouggoth",
    ["The Three Pillars of Diatz"] = "diatz",
    ["The Titans' Keep"] = "titan",
    ["The Tournament of Illoria"] = "illoria",
    ["The Town of Solan"] = "solan",
    ["The Tree of Life"] = "tol",
    ["The Trouble with Gwillimberry"] = "gwillim",
    ["The Uncharted Oceans"] = "uncharted",
    ["The UnderDark"] = "underdark",
    ["The Upper Planes"] = "uplanes",
    ["The Uprising"] = "uprising",
    ["The Were Wood"] = "werewood",
    ["The Witches of Omen Tor"] = "omentor",
    ["The Wobbly Woes of Woobleville"] = "wooble",
    ["The Wood Elves of Nalondir"] = "woodelves",
    ["The Yurgach Domain"] = "yurgach",
    ["Tilule Rehabilitation Clinic"] = "tilule",
    ["Tir na nOg"] = "tirna",
    ["Tournament Camps"] = "camps",
    ["Transcendece"] = "transcend",
    ["Tribal Origins"] = "origins",
    ["Tumari's Diner"] = "diner",
    ["Umari's Castle"] = "umari",
    ["Unearthly Bonds"] = "bonds",
    ["Verdure Estate"] = "verdure",
    ["Vidblain, the Ever Dark"] = "vidblain",
    ["War of the Wizards"] = "wizards",
    ["Warrior's Training Camp"] = "wtc",
    ["Wayward Alehouse"] = "alehouse",
    ["Weather Observatory"] = "weather",
    ["Wedded Bliss"] = "bliss",
    ["Wildwood"] = "wildwood",
    ["Winds of Fate"] = "winds",
    ["Winterlands"] = "winter",
    ["Xyl's Mosaic"] = "xylmos",
    ["Yggdrasil: The World Tree"] = "ygg",
    ["Zangar's Demonic Grotto"] = "zangar",
    -- New areas
    ["The Keep of the Asherodan"] = "asherodan",
    ["Bloodlust Dungeon"] = "dungeon",
    ["Svrogan's Logging Camp"] = "logging"
}
