local areaTable = {
    {name = "Bloodlust Dungeon", keyword = 'dungeon', start = 0, vidblain = false, noquest = false, min = 200, max = 201, lock = 201},
    {name = "The Desert Prison", keyword = 'desert', start = 20186, vidblain = false, noquest = false, min = 130, max = 201, lock = 110},
    {name = "The Dungeon of Doom", keyword = 'dundoom', start = 25661, vidblain = false, noquest = false, min = 200, max = 201, lock = 180},
    {name = "The Earth Lords", keyword = 'earthlords', start = 42000, vidblain = false, noquest = false, min = 200, max = 201, lock = 175},
    {name = "The Empire of Aiighialla", keyword = 'empire', start = 32203, vidblain = false, noquest = false, min = 140, max = 180, lock = 100},
    {name = "The Fabled City of Stone", keyword = 'stone', start = 11386, vidblain = false, noquest = false, min = 70, max = 130, lock = 40},
    {name = "The Flying Citadel", keyword = 'citadel', start = 14963, vidblain = false, noquest = false, min = 50, max = 70, lock = 20},
    {name = "The Gauntlet", keyword = 'gauntlet', start = 31652, vidblain = false, noquest = false, min = 5, max = 30, lock = 0},
    {name = "The Gladiator's Arena", keyword = 'arena', start = 25768, vidblain = false, noquest = false, min = 80, max = 100, lock = 0},
    {name = "The Glamdursil", keyword = 'glamdursil', start = 35055, vidblain = false, noquest = false, min = 170, max = 201, lock = 140},
    {name = "The Grand City of Aylor", keyword = 'aylor', start = 32418, vidblain = false, noquest = false, min = 1, max = 201, lock = 0},
    {name = "The Great Salt Flats", keyword = 'salt', start = 4538, vidblain = false, noquest = false, min = 40, max = 50, lock = 15},
    {name = "The Keep of Kearvek", keyword = 'kearvek', start = 29722, vidblain = false, noquest = false, min = 175, max = 201, lock = 140},
    {name = "The Killing Fields", keyword = 'fields', start = 29232, vidblain = false, noquest = false, min = 60, max = 80, lock = 40},
    {name = "The Labyrinth", keyword = 'labyrinth', start = 31405, vidblain = false, noquest = false, min = 30, max = 60, lock = 15},
    {name = "The Land of the Beer Goblins", keyword = 'beer', start = 20062, vidblain = false, noquest = false, min = 1, max = 20, lock = 0},
    {name = "The Lower Planes", keyword = 'lplanes', start = 29364, vidblain = false, noquest = false, min = 70, max = 100, lock = 50},
    {name = "The Marshlands of Agroth", keyword = 'agroth', start = 11027, vidblain = false, noquest = false, min = 105, max = 125, lock = 60},
    {name = "The Misty Shores of Yarr", keyword = 'yarr', start = 30281, vidblain = false, noquest = false, min = 115, max = 135, lock = 80},
    {name = "The Monastery", keyword = 'monastery', start = 15756, vidblain = false, noquest = false, min = 90, max = 120, lock = 50},
    {name = "The Nine Hells", keyword = 'ninehells', start = 4613, vidblain = false, noquest = false, min = 180, max = 201, lock = 170},
    {name = "The Old Cathedral", keyword = 'cathedral', start = 27497, vidblain = false, noquest = false, min = 50, max = 80, lock = 25},
    {name = "The Path of the Believer", keyword = 'believer', start = 25940, vidblain = false, noquest = false, min = 1, max = 10, lock = 0},
    {name = "The Realm of Infamy", keyword = 'infamy', start = 26641, vidblain = false, noquest = false, min = 200, max = 201, lock = 190},
    {name = "The Reman Conspiracy", keyword = 'remcon', start = 25837, vidblain = false, noquest = false, min = 130, max = 170, lock = 95},
    {name = "The Shadows of Minos", keyword = 'minos', start = 20472, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "The Silver Volcano", keyword = 'volcano', start = 6091, vidblain = false, noquest = false, min = 30, max = 100, lock = 0},
    {name = "The Slaughter House", keyword = 'slaughter', start = 1601, vidblain = false, noquest = false, min = 120, max = 145, lock = 95},
    {name = "The Stuff of Shadows", keyword = 'stuff', start = 40400, vidblain = false, noquest = false, min = 110, max = 130, lock = 30},
    {name = "The Town of Solan", keyword = 'solan', start = 23713, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "The Uprising", keyword = 'uprising', start = 15382, vidblain = false, noquest = false, min = 120, max = 160, lock = 100},
    {name = "The Wobbly Woes of Woobleville", keyword = 'wooble', start = 11335, vidblain = false, noquest = false, min = 40, max = 60, lock = 0},
    {name = "Tir na nOg", keyword = 'tirna', start = 20136, vidblain = false, noquest = false, min = 130, max = 150, lock = 100},
    {name = "Tournament Camps", keyword = 'camps', start = 4714, vidblain = false, noquest = false, min = 1, max = 10, lock = 0},
    {name = "Unearthly Bonds", keyword = 'bonds', start = 23411, vidblain = false, noquest = false, min = 140, max = 170, lock = 0},
    {name = "A Genie's Last Wish", keyword = 'geniewish', start = 38464, vidblain = false, noquest = true, min = 200, max = 201, lock = 200},
    {name = "Weather Observatory", keyword = 'weather', start = 40499, vidblain = false, noquest = false, min = 20, max = 40, lock = 0},
    {name = "A Peaceful Giant Village", keyword = 'village', start = 30850, vidblain = false, noquest = false, min = 130, max = 160, lock = 100},
    {name = "Aardington Estate", keyword = 'aardington', start = 47509, vidblain = false, noquest = false, min = 70, max = 90, lock = 0},
    {name = "Aardwolf Zoological Park", keyword = 'zoo', start = 5920, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "Adventures in Sendhia", keyword = 'sendhian', start = 20288, vidblain = true, noquest = false, min = 5, max = 50, lock = 0},
    {name = "Xyl's Mosaic", keyword = 'xylmos', start = 472, vidblain = false, noquest = false, min = 100, max = 120, lock = 80},
    {name = "Afterglow", keyword = 'afterglow', start = 38134, vidblain = false, noquest = false, min = 200, max = 201, lock = 0},
    {name = "Alagh, the Blood Lands", keyword = 'alagh', start = 3224, ct = 4, vidblain = false, noquest = false, min = 1, max = 210, lock = 0},
    {name = "All in a Fayke Day", keyword = 'fayke', start = 30418, vidblain = false, noquest = false, min = 10, max = 30, lock = 0},
    {name = "An Auspicious Star's Zenith", keyword = 'zenith', start = 23681, vidblain = false, noquest = false, min = 200, max = 201, lock = 150},
    {name = "Ancient Greece", keyword = 'greece', start = 2089, vidblain = false, noquest = false, min = 20, max = 50, lock = 0},
    {name = "Andolor's Ocean Adventure Park", keyword = 'oceanpark', start = 39600, vidblain = false, noquest = false, min = 200, max = 201, lock = 175},
    {name = "Annwn", keyword = 'annwn', start = 28963, vidblain = false, noquest = false, min = 160, max = 180, lock = 140},
    {name = "Snuckles Village", keyword = 'snuckles', start = 182, vidblain = false, noquest = false, min = 80, max = 100, lock = 65},
    {name = "Storm Mountain", keyword = 'storm', start = 6304, vidblain = false, noquest = false, min = 10, max = 35, lock = 0},
    {name = "Arisian Realm", keyword = 'arisian', start = 28144, vidblain = false, noquest = false, min = 150, max = 170, lock = 130},
    {name = "Sundered Vale", keyword = 'vale', start = 1036, vidblain = false, noquest = false, min = 5, max = 20, lock = 0},
    {name = "Swordbreaker's Hoard", keyword = 'hoard', start = 1675, vidblain = false, noquest = false, min = 5, max = 50, lock = 0},
    {name = "Tairayden Peninsula", keyword = 'peninsula', start = 35701, vidblain = false, noquest = false, min = 110, max = 130, lock = 80},
    {name = "Atlantis", keyword = 'atlantis', start = 10573, vidblain = false, noquest = false, min = 20, max = 40, lock = 0},
    {name = "Takeda's Warcamp", keyword = 'takeda', start = 15952, vidblain = false, noquest = false, min = 140, max = 201, lock = 115},
    {name = "Tanra'vea", keyword = 'tanra', start = 46913, vidblain = false, noquest = false, min = 180, max = 201, lock = 170},
    {name = "Black Lagoon", keyword = 'lagoon', start = 30549, vidblain = false, noquest = false, min = 155, max = 195, lock = 120},
    {name = "The Abyssal Caverns of Sahuagin", keyword = 'sahuagin', start = 34592, vidblain = false, noquest = false, min = 140, max = 160, lock = 100},
    {name = "Brightsea and Glimmerdim", keyword = 'glimmerdim', start = 26252, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "Canyon Memorial Hospital", keyword = 'canyon', start = 25551, vidblain = false, noquest = false, min = 5, max = 30, lock = 0},
    {name = "Castle Vlad-Shamir", keyword = 'vlad', start = 15970, vidblain = false, noquest = false, min = 50, max = 80, lock = 30},
    {name = "Chakra Spire", keyword = 'chakra', start = 0, vidblain = false, noquest = false, min = 180, max = 201, lock = 0},
    {name = "Chaprenula's Laboratory", keyword = 'lab', start = 28684, vidblain = false, noquest = false, min = 5, max = 15, lock = 0},
    {name = "The Blighted Tundra of Andarin", keyword = 'andarin', start = 2399, vidblain = false, noquest = false, min = 35, max = 60, lock = 0},
    {name = "Christmas Vacation", keyword = 'xmas', start = 6212, vidblain = false, noquest = false, min = 110, max = 150, lock = 100},
    {name = "The Blood Sanctum", keyword = 'sanctum', start = 15307, vidblain = false, noquest = false, min = 180, max = 201, lock = 180},
    {name = "The Broken Halls of Horath", keyword = 'horath', start = 91, vidblain = false, noquest = false, min = 120, max = 170, lock = 90},
    {name = "Crossroads of Fortune", keyword = 'fortune', start = 38561, vidblain = false, noquest = false, min = 201, max = 201, lock = 201},
    {name = "Crynn's Church", keyword = 'crynn', start = 43800, vidblain = false, noquest = false, min = 195, max = 201, lock = 185},
    {name = "Dark Elf Stronghold", keyword = 'stronghold', start = 20572, vidblain = false, noquest = false, min = 90, max = 125, lock = 40},
    {name = "Death's Manor", keyword = 'manor', start = 10621, vidblain = false, noquest = false, min = 20, max = 40, lock = 0},
    {name = "Deathtrap Dungeon", keyword = 'deathtrap', start = 1767, vidblain = false, noquest = false, min = 80, max = 130, lock = 60},
    {name = "Den of Thieves", keyword = 'thieves', start = 7, vidblain = false, noquest = false, min = 5, max = 20, lock = 0},
    {name = "Descent to Hell", keyword = 'hell', start = 30984, vidblain = false, noquest = false, min = 35, max = 55, lock = 0},
    {name = "Desert Doom", keyword = 'ddoom', start = 4193, vidblain = false, noquest = false, min = 135, max = 150, lock = 115},
    {name = "Dhal'Gora Outlands", keyword = 'dhalgora', start = 16755, vidblain = false, noquest = false, min = 10, max = 50, lock = 0},
    {name = "Diamond Soul Revelation", keyword = 'dsr', start = 30030, vidblain = false, noquest = false, min = 35, max = 85, lock = 25},
    {name = "Dortmund", keyword = 'dortmund', start = 16577, vidblain = false, noquest = false, min = 5, max = 25, lock = 0},
    {name = "Dread Tower", keyword = 'dread', start = 26075, vidblain = false, noquest = false, min = 160, max = 180, lock = 140},
    {name = "Dunes in Gold", keyword = 'dunes', start = 42170, vidblain = false, noquest = false, min = 180, max = 201, lock = 160},
    {name = "Dusk Valley", keyword = 'duskvalley', start = 37301, vidblain = false, noquest = false, min = 100, max = 120, lock = 100},
    {name = "Earth Plane 4", keyword = 'earthplane', start = 1354, vidblain = false, noquest = false, min = 50, max = 80, lock = 30},
    {name = "Elemental Chaos", keyword = 'elemental', start = 41624, vidblain = false, noquest = false, min = 90, max = 150, lock = 0},
    {name = "Empyrean, Streets of Downfall", keyword = 'empyrean', start = 14042, vidblain = false, noquest = false, min = 170, max = 200, lock = 140},
    {name = "Entrance to Hades", keyword = 'hades', start = 29161, vidblain = false, noquest = false, min = 190, max = 201, lock = 160},
    {name = "Eternal Autumn", keyword = 'autumn', start = 13839, vidblain = false, noquest = false, min = 170, max = 201, lock = 0},
    {name = "Faerie Tales II", keyword = 'ftii', start = 26673, vidblain = false, noquest = false, min = 120, max = 150, lock = 100},
    {name = "Faerie Tales", keyword = 'ft1', start = 1205, vidblain = false, noquest = false, min = 100, max = 120, lock = 90},
    {name = "Fantasy Fields", keyword = 'fantasy', start = 15205, vidblain = false, noquest = false, min = 5, max = 30, lock = 0},
    {name = "Fellchantry", keyword = 'chantry', start = 0, vidblain = false, noquest = false, min = 150, max = 170, lock = 130},
    {name = "Foolish Promises", keyword = 'promises', start = 25819, vidblain = false, noquest = false, min = 130, max = 140, lock = 115},
    {name = "Fort Terramire", keyword = 'terramire', start = 4493, vidblain = false, noquest = false, min = 10, max = 35, lock = 0},
    {name = "Gallows Hill", keyword = 'gallows', start = 4344, vidblain = false, noquest = false, min = 1, max = 30, lock = 0},
    {name = "Gelidus", keyword = 'gelidus', start = 18780, ct = 2, vidblain = false, noquest = false, min = 1, max = 210, lock = 0},
    {name = "Giant's Pet Store", keyword = 'petstore', start = 995, vidblain = false, noquest = false, min = 5, max = 20, lock = 0},
    {name = "Gilda And The Dragon", keyword = 'gilda', start = 4243, vidblain = false, noquest = false, min = 120, max = 140, lock = 80},
    {name = "Gnoll's Quarry", keyword = 'quarry', start = 23510, vidblain = false, noquest = false, min = 105, max = 125, lock = 0},
    {name = "Gold Rush", keyword = 'goldrush', start = 15014, vidblain = false, noquest = false, min = 30, max = 70, lock = 15},
    {name = "Guardian's Spyre of Knowledge", keyword = 'spyreknow', start = 34800, vidblain = false, noquest = false, min = 10, max = 30, lock = 0},
    {name = "Wayfarer's Caravan", keyword = 'caravan', start = 16071, vidblain = false, noquest = false, min = 200, max = 201, lock = 0},
    {name = "Halls of the Damned", keyword = 'damned', start = 10469, vidblain = false, noquest = false, min = 95, max = 115, lock = 70},
    {name = "Hatchling Aerie", keyword = 'hatchling', start = 34670, vidblain = false, noquest = false, min = 5, max = 45, lock = 0},
    {name = "Hedgehogs' Paradise", keyword = 'hedge', start = 15146, vidblain = false, noquest = false, min = 60, max = 80, lock = 0},
    {name = "Helegear Sea", keyword = 'helegear', start = 30699, vidblain = false, noquest = false, min = 160, max = 180, lock = 130},
    {name = "Hotel Orlando", keyword = 'orlando', start = 30331, vidblain = false, noquest = false, min = 1, max = 20, lock = 0},
    {name = "House of Cards", keyword = 'cards', start = 6255, vidblain = false, noquest = false, min = 120, max = 150, lock = 90},
    {name = "Icefall", keyword = 'icefall', start = 38701, vidblain = false, noquest = true, min = 200, max = 201, lock = 200},
    {name = "Imagi's Nation", keyword = 'imagi', start = 36800, vidblain = false, noquest = false, min = 140, max = 160, lock = 0},
    {name = "Imperial Nation", keyword = 'imperial', start = 16966, vidblain = true, noquest = false, min = 65, max = 201, lock = 20},
    {name = "Into the Long Night", keyword = 'longnight', start = 26367, vidblain = false, noquest = false, min = 100, max = 200, lock = 60},
    {name = "Insanitaria", keyword = 'insan', start = 6850, vidblain = false, noquest = false, min = 95, max = 115, lock = 0},
    {name = "Intrigues of Times Past", keyword = 'times', start = 28463, vidblain = false, noquest = false, min = 175, max = 201, lock = 150},
    {name = "Jotunheim", keyword = 'jotun', start = 31508, vidblain = false, noquest = false, min = 1, max = 40, lock = 0},
    {name = "Jungles of Verume", keyword = 'verume', start = 30607, vidblain = false, noquest = false, min = 10, max = 40, lock = 0},
    {name = "Keep of the Kobaloi", keyword = 'kobaloi', start = 10691, vidblain = false, noquest = false, min = 10, max = 201, lock = 0},
    {name = "Kerofk", keyword = 'kerofk', start = 16405, vidblain = false, noquest = false, min = 5, max = 30, lock = 0},
    {name = "Ketu Uplands", keyword = 'ketu', start = 35114, vidblain = false, noquest = false, min = 200, max = 201, lock = 0},
    {name = "Kiksaadi Cove", keyword = 'cove', start = 49941, vidblain = false, noquest = false, min = 190, max = 200, lock = 150},
    {name = "Kimr's Farm", keyword = 'farm', start = 10676, vidblain = false, noquest = false, min = 1, max = 5, lock = 0},
    {name = "Kingdom of Ahner", keyword = 'ahner', start = 30129, vidblain = false, noquest = false, min = 20, max = 50, lock = 0},
    {name = "Raganatittu", keyword = 'raga', start = 19861, vidblain = false, noquest = false, min = 40, max = 60, lock = 0},
    {name = "Realm of Deneria", keyword = 'deneria', start = 35006, vidblain = false, noquest = false, min = 60, max = 85, lock = 0},
    {name = "Realm of the Firebird", keyword = 'firebird', start = 32885, vidblain = false, noquest = false, min = 80, max = 110, lock = 50},
    {name = "Land of Legend", keyword = 'legend', start = 16224, vidblain = false, noquest = false, min = 1, max = 20, lock = 0},
    {name = "Sho'aram, Castle in the Sand", keyword = 'sandcastle', start = 37701, vidblain = false, noquest = false, min = 10, max = 30, lock = 0},
    {name = "Siren's Oasis Resort", keyword = 'sirens', start = 16298, vidblain = false, noquest = false, min = 5, max = 15, lock = 0},
    {name = "Mount duNoir", keyword = 'dunoir', start = 14222, vidblain = false, noquest = false, min = 175, max = 201, lock = 160},
    {name = "Mudwog's Swamp", keyword = 'mudwog', start = 2347, vidblain = false, noquest = false, min = 30, max = 40, lock = 0},
    {name = "Nanjiki Ruins", keyword = 'nanjiki', start = 11203, vidblain = false, noquest = false, min = 140, max = 160, lock = 110},
    {name = "Nebulous Horizon", keyword = 'horizon', start = 31959, vidblain = false, noquest = false, min = 200, max = 201, lock = 185},
    {name = "The Amusement Park", keyword = 'amusement', start = 29282, vidblain = false, noquest = false, min = 5, max = 20, lock = 0},
    {name = "Nenukon and the Far Country", keyword = 'nenukon', start = 31784, vidblain = false, noquest = false, min = 70, max = 100, lock = 50},
    {name = "The Astral Travels", keyword = 'astral', start = 27882, vidblain = false, noquest = false, min = 180, max = 201, lock = 150},
    {name = "Northstar", keyword = 'northstar', start = 11127, vidblain = false, noquest = false, min = 70, max = 140, lock = 50},
    {name = "Nottingham", keyword = 'nottingham', start = 11077, vidblain = false, noquest = false, min = 190, max = 201, lock = 180},
    {name = "The Call of Heroes", keyword = 'callhero', start = 33031, vidblain = false, noquest = false, min = 1, max = 15, lock = 0},
    {name = "Onyx Bazaar", keyword = 'bazaar', start = 34454, vidblain = false, noquest = false, min = 35, max = 55, lock = 0},
    {name = "Ookushka Garrison", keyword = 'ooku', start = 39000, vidblain = false, noquest = false, min = 200, max = 201, lock = 160},
    {name = "The Coral Kingdom", keyword = 'coral', start = 4565, vidblain = false, noquest = false, min = 30, max = 50, lock = 0},
    {name = "Plains of Nulan'Boar", keyword = 'nulan', start = 37900, vidblain = false, noquest = false, min = 60, max = 80, lock = 0},
    {name = "Pompeii", keyword = 'pompeii', start = 57, vidblain = false, noquest = false, min = 90, max = 110, lock = 70},
    {name = "Prosper's Island", keyword = 'prosper', start = 28268, vidblain = false, noquest = false, min = 100, max = 125, lock = 70},
    {name = "Qong", keyword = 'qong', start = 16115, vidblain = false, noquest = false, min = 200, max = 220, lock = 0},
    {name = "The Dark Temple of Zyian", keyword = 'zyian', start = 729, vidblain = false, noquest = false, min = 130, max = 150, lock = 100},
    {name = "The Darkside of the Fractured Lands", keyword = 'darkside', start = 15060, vidblain = false, noquest = false, min = 40, max = 60, lock = 0},
    {name = "The Drageran Empire", keyword = 'drageran', start = 25894, vidblain = false, noquest = false, min = 130, max = 150, lock = 100},
    {name = "The Eighteenth Dynasty", keyword = 'dynasty', start = 30799, vidblain = false, noquest = false, min = 120, max = 140, lock = 90},
    {name = "Realm of the Sacred Flame", keyword = 'firenation', start = 41879, vidblain = false, noquest = false, min = 200, max = 201, lock = 180},
    {name = "Realm of the Zodiac", keyword = 'zodiac', start = 15857, vidblain = false, noquest = false, min = 20, max = 30, lock = 0},
    {name = "Rebellion of the Nix", keyword = 'rebellion', start = 10305, vidblain = false, noquest = false, min = 150, max = 190, lock = 120},
    {name = "The Forest of Li'Dnesh", keyword = 'lidnesh', start = 27995, vidblain = false, noquest = false, min = 1, max = 10, lock = 0},
    {name = "Sagewood Grove", keyword = 'sagewood', start = 28754, vidblain = false, noquest = false, min = 150, max = 180, lock = 130},
    {name = "Sanctity of Eternal Damnation", keyword = 'sanctity', start = 10518, vidblain = false, noquest = false, min = 100, max = 201, lock = 75},
    {name = "Sen'narre Lake", keyword = 'sennarre', start = 15491, vidblain = false, noquest = false, min = 1, max = 20, lock = 0},
    {name = "Seven Wonders", keyword = 'wonders', start = 32981, vidblain = false, noquest = false, min = 100, max = 120, lock = 70},
    {name = "Shadow's End", keyword = 'shadowsend', start = 40096, vidblain = false, noquest = false, min = 200, max = 201, lock = 190},
    {name = "Sheila's Cat Sanctuary", keyword = 'cats', start = 40900, vidblain = false, noquest = false, min = 25, max = 35, lock = 0},
    {name = "The Imperial City of Reme", keyword = 'reme', start = 32703, vidblain = false, noquest = false, min = 30, max = 100, lock = 15},
    {name = "The Infestation", keyword = 'infest', start = 16165, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "The Land of Oz", keyword = 'landofoz', start = 510, vidblain = false, noquest = false, min = 40, max = 70, lock = 20},
    {name = "The Maelstrom", keyword = 'maelstrom', start = 38058, vidblain = false, noquest = false, min = 20, max = 45, lock = 0},
    {name = "The Mountains of Desolation", keyword = 'desolation', start = 19532, vidblain = false, noquest = false, min = 130, max = 175, lock = 100},
    {name = "The Nyne Woods", keyword = 'nynewoods', start = 23562, vidblain = false, noquest = false, min = 200, max = 201, lock = 175},
    {name = "The Palace of Song", keyword = 'songpalace', start = 47013, vidblain = false, noquest = false, min = 60, max = 80, lock = 30},
    {name = "The Partroxis", keyword = 'partroxis', start = 5814, vidblain = false, noquest = false, min = 180, max = 201, lock = 150},
    {name = "The Realm of the Hawklords", keyword = 'hawklord', start = 40550, vidblain = false, noquest = false, min = 80, max = 100, lock = 0},
    {name = "The Relinquished Tombs", keyword = 'tombs', start = 15385, vidblain = false, noquest = false, min = 70, max = 100, lock = 50},
    {name = "The Ruins of Diamond Reach", keyword = 'ruins', start = 16805, vidblain = false, noquest = false, min = 60, max = 120, lock = 35},
    {name = "The Ruins of Stormhaven", keyword = 'stormhaven', start = 20649, vidblain = false, noquest = false, min = 150, max = 201, lock = 130},
    {name = "The Sanguine Tavern", keyword = 'sanguine', start = 15436, vidblain = false, noquest = false, min = 120, max = 140, lock = 70},
    {name = "The Scarred Lands", keyword = 'scarred', start = 34036, vidblain = false, noquest = false, min = 90, max = 110, lock = 60},
    {name = "The School of Horror", keyword = 'soh', start = 25611, vidblain = false, noquest = false, min = 125, max = 201, lock = 110},
    {name = "The Southern Ocean", keyword = 'southern', start = 5192, ct = 1, vidblain = false, noquest = false, min = 1, max = 210, lock = 0},
    {name = "The Temple of Shal'indrael", keyword = 'temple', start = 31597, vidblain = false, noquest = false, min = 180, max = 201, lock = 160},
    {name = "The Temple of Shouggoth", keyword = 'shouggoth', start = 34087, vidblain = false, noquest = false, min = 10, max = 50, lock = 0},
    {name = "The Three Pillars of Diatz", keyword = 'diatz', start = 1254, vidblain = false, noquest = false, min = 60, max = 80, lock = 25},
    {name = "The Titans' Keep", keyword = 'titan', start = 38234, vidblain = false, noquest = false, min = 200, max = 201, lock = 200},
    {name = "The Tournament of Illoria", keyword = 'illoria', start = 10420, vidblain = false, noquest = false, min = 70, max = 90, lock = 40},
    {name = "The Tree of Life", keyword = 'tol', start = 16325, vidblain = false, noquest = false, min = 170, max = 201, lock = 150},
    {name = "The Trouble with Gwillimberry", keyword = 'gwillim', start = 25974, vidblain = false, noquest = false, min = 190, max = 201, lock = 185},
    {name = "The Uncharted Oceans", keyword = 'uncharted', start = 7701, ct = 5, vidblain = false, noquest = false, min = 1, max = 210, lock = 0},
    {name = "The UnderDark", keyword = 'underdark', start = 27341, vidblain = false, noquest = false, min = 15, max = 50, lock = 0},
    {name = "The Upper Planes", keyword = 'uplanes', start = 29364, vidblain = false, noquest = false, min = 60, max = 100, lock = 50},
    {name = "The Were Wood", keyword = 'werewood', start = 30956, vidblain = false, noquest = false, min = 200, max = 201, lock = 180},
    {name = "The Witches of Omen Tor", keyword = 'omentor', start = 15579, vidblain = true, noquest = false, min = 160, max = 201, lock = 130},
    {name = "The Wood Elves of Nalondir", keyword = 'woodelves', start = 32199, vidblain = false, noquest = false, min = 5, max = 30, lock = 0},
    {name = "The Yurgach Domain", keyword = 'yurgach', start = 29450, vidblain = false, noquest = false, min = 50, max = 100, lock = 24},
    {name = "Tilule Rehabilitation Clinic", keyword = 'tilule', start = 39771, vidblain = false, noquest = false, min = 50, max = 80, lock = 0},
    {name = "Transcendece", keyword = 'transcend', start = 0, vidblain = false, noquest = true, min = 200, max = 201, lock = 180},
    {name = "Tribal Origins", keyword = 'origins', start = 35900, vidblain = false, noquest = false, min = 165, max = 190, lock = 150},
    {name = "Tumari's Diner", keyword = 'diner', start = 36700, vidblain = false, noquest = false, min = 125, max = 145, lock = 100},
    {name = "Umari's Castle", keyword = 'umari', start = 36601, vidblain = false, noquest = false, min = 195, max = 201, lock = 175},
    {name = "Verdure Estate", keyword = 'verdure', start = 24090, vidblain = false, noquest = false, min = 120, max = 140, lock = 80},
    {name = "Vidblain, the Ever Dark", keyword = 'vidblain', start = 33570, ct = 6, vidblain = true, noquest = false, min = 1, max = 210, lock = 0},
    {name = "War of the Wizards", keyword = 'wizards', start = 31316, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "Warrior's Training Camp", keyword = 'wtc', start = 37895, vidblain = false, noquest = false, min = 10, max = 20, lock = 0},
    {name = "Wayward Alehouse", keyword = 'alehouse', start = 885, vidblain = false, noquest = false, min = 70, max = 90, lock = 0},
    {name = "Wedded Bliss", keyword = 'bliss', start = 29988, vidblain = false, noquest = false, min = 80, max = 100, lock = 50},
    {name = "Wildwood", keyword = 'wildwood', start = 322, vidblain = false, noquest = false, min = 10, max = 40, lock = 0},
    {name = "Winds of Fate", keyword = 'winds', start = 39900, vidblain = false, noquest = true, min = 200, max = 201, lock = 0},
    {name = "Winterlands", keyword = 'winter', start = 1306, vidblain = false, noquest = false, min = 150, max = 170, lock = 110},
    {name = "Zangar's Demonic Grotto", keyword = 'zangar', start = 6164, vidblain = false, noquest = false, min = 40, max = 60, lock = 30},
    {name = "The Keep of the Asherodan", keyword = 'asherodan', start = 37400, vidblain = true, noquest = false, min = 80, max = 90, lock = 70},
    {name = "Svrogan's Logging Camp", keyword = 'logging', start = 31254, vidblain = false, noquest = false, min = 80, max = 110, lock = 0},
    {name = "Yggdrasil: The World Tree", keyword = 'ygg', start = 24186, vidblain = false, noquest = false, min = 180, max = 201, lock = 150},
    {name = "Cradlebrook", keyword = 'cradle', start = 11267, vidblain = false, noquest = false, min = 30, max = 50, lock = 0},
    {name = "Cloud City of Gnomalin", keyword = 'gnomalin', start = 34397, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "Child's Play", keyword = 'childsplay', start = 678, vidblain = false, noquest = false, min = 5, max = 25, lock = 0},
    {name = "Black Rose", keyword = 'blackrose', start = 1817, vidblain = false, noquest = false, min = 175, max = 201, lock = 140},
    {name = "Battlefields of Adaldar", keyword = 'adaldar', start = 34400, vidblain = false, noquest = false, min = 150, max = 180, lock = 120},
    {name = "Avian Kingdom", keyword = 'avian', start = 4334, vidblain = false, noquest = false, min = 170, max = 190, lock = 140},
    {name = "Ascension Bluff Nursing Home", keyword = 'nursing', start = 31977, vidblain = false, noquest = false, min = 100, max = 120, lock = 90},
    {name = "Artificer's Mayhem", keyword = 'mayhem', start = 1866, vidblain = false, noquest = false, min = 180, max = 201, lock = 140},
    {name = "Art of Melody", keyword = 'melody', start = 14172, vidblain = false, noquest = false, min = 1, max = 15, lock = 0},
    {name = "Arboretum", keyword = 'arboretum', start = 39100, vidblain = false, noquest = false, min = 110, max = 130, lock = 80},
    {name = "Anthrox", keyword = 'anthrox', start = 3993, vidblain = false, noquest = false, min = 80, max = 110, lock = 50},
    {name = "Aerial City of Cineko", keyword = 'cineko', start = 1507, vidblain = false, noquest = false, min = 15, max = 30, lock = 0},
    {name = "A Magical Hodgepodge", keyword = 'hodgepodge', start = 30469, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "Island of Lost Time", keyword = 'losttime', start = 28584, vidblain = false, noquest = false, min = 80, max = 110, lock = 50},
    {name = "Jenny's Tavern", keyword = 'jenny', start = 29637, vidblain = false, noquest = false, min = 50, max = 100, lock = 24},
    {name = "Paradise Lost", keyword = 'paradise', start = 29624, vidblain = false, noquest = false, min = 50, max = 70, lock = 20},
    {name = "Radiance Woods", keyword = 'radiance', start = 19805, vidblain = false, noquest = false, min = 200, max = 201, lock = 0},
    {name = "Olde Worlde Carnivale", keyword = 'carnivale', start = 28635, vidblain = false, noquest = false, min = 5, max = 35, lock = 0},
    {name = "New Thalos", keyword = 'newthalos', start = 23853, vidblain = false, noquest = false, min = 10, max = 35, lock = 0},
    {name = "Necromancers' Guild", keyword = 'necro', start = 29922, vidblain = false, noquest = false, min = 15, max = 30, lock = 0},
    {name = "Kul Tiras", keyword = 'kultiras', start = 31161, vidblain = false, noquest = false, min = 15, max = 30, lock = 10},
    {name = "Masquerade Island", keyword = 'masq', start = 29840, vidblain = false, noquest = false, min = 100, max = 130, lock = 80},
    {name = "Living Mines of Dak'Tai", keyword = 'livingmine', start = 37008, vidblain = false, noquest = false, min = 110, max = 140, lock = 70},
    {name = "Storm Ships of Lem-Dagor", keyword = 'lemdagor', start = 1966, vidblain = false, noquest = false, min = 50, max = 100, lock = 30},
    {name = "Tai'rha Laym", keyword = 'laym', start = 6005, vidblain = false, noquest = false, min = 70, max = 110, lock = 40},
    {name = "Thandeld's Conflict", keyword = 'conflict', start = 27711, vidblain = false, noquest = false, min = 20, max = 50, lock = 0},
    {name = "The Amazon Nation", keyword = 'amazon', start = 1409, vidblain = false, noquest = false, min = 120, max = 201, lock = 100},
    {name = "The Archipelago of Entropy", keyword = 'entropy', start = 29773, vidblain = false, noquest = false, min = 120, max = 150, lock = 90},
    {name = "The Aylorian Academy", keyword = 'academy', start = 35233, vidblain = false, noquest = false, min = 1, max = 201, lock = 0},
    {name = "The Blood Opal of Rauko'ra", keyword = 'raukora', start = 6040, vidblain = false, noquest = false, min = 125, max = 201, lock = 100},
    {name = "The Continent of Mesolar", keyword = 'mesolar', start = 12664, ct = 0, vidblain = false, noquest = false, min = 1, max = 210, lock = 0},
    {name = "The Cougarian Queendom", keyword = 'cougarian', start = 14311, vidblain = false, noquest = false, min = 140, max = 160, lock = 100},
    {name = "The Council of the Wyrm", keyword = 'wyrm', start = 28847, vidblain = false, noquest = false, min = 190, max = 201, lock = 175},
    {name = "The Covenant of Mistridge", keyword = 'mistridge', start = 4491, vidblain = false, noquest = false, min = 160, max = 201, lock = 120},
    {name = "The Cracks of Terra", keyword = 'terra', start = 19679, vidblain = false, noquest = false, min = 200, max = 201, lock = 200},
    {name = "The Curse of the Midnight Fens", keyword = 'fens', start = 16528, vidblain = false, noquest = false, min = 200, max = 201, lock = 160},
    {name = "The Dark Continent, Abend", keyword = 'abend', start = 24909, ct = 3, vidblain = false, noquest = false, min = 1, max = 210, lock = 0},
    {name = "The DarkLight", keyword = 'darklight', start = 19642, vidblain = true, noquest = false, min = 60, max = 120, lock = 30},
    {name = "The Deadlights", keyword = 'deadlights', start = 16856, vidblain = false, noquest = false, min = 175, max = 201, lock = 135},
    {name = "The Empire of Talsa", keyword = 'talsa', start = 26917, vidblain = false, noquest = false, min = 70, max = 130, lock = 40},
    {name = "The Fire Swamp", keyword = 'fireswamp', start = 34755, vidblain = false, noquest = false, min = 5, max = 15, lock = 0},
    {name = "The First Ascent", keyword = 'ascent', start = 43150, vidblain = false, noquest = false, min = 5, max = 15, lock = 0},
    {name = "The Fractured Lands", keyword = 'fractured', start = 17033, vidblain = false, noquest = false, min = 20, max = 40, lock = 0},
    {name = "The Gathering Horde", keyword = 'gathering', start = 36451, vidblain = false, noquest = false, min = 140, max = 170, lock = 110},
    {name = "The Goblin Fortress", keyword = 'fortress', start = 31835, vidblain = false, noquest = false, min = 60, max = 80, lock = 30},
    {name = "The Graveyard", keyword = 'graveyard', start = 28918, vidblain = false, noquest = false, min = 5, max = 15, lock = 0},
    {name = "The Great City of Knossos", keyword = 'knossos', start = 28193, vidblain = false, noquest = false, min = 60, max = 80, lock = 30},
    {name = "The Icy Caldera of Mauldoon", keyword = 'caldera', start = 26341, vidblain = false, noquest = false, min = 190, max = 201, lock = 150},
    {name = "The Chessboard", keyword = 'chessboard', start = 25513, vidblain = false, noquest = false, min = 5, max = 20, lock = 0},
    {name = "The Chasm and The Catacombs", keyword = 'chasm', start = 29446, vidblain = false, noquest = false, min = 10, max = 20, lock = 0},
    {name = "The Cataclysm", keyword = 'cataclysm', start = 19976, vidblain = false, noquest = false, min = 150, max = 201, lock = 120},
    {name = "Kingsholm", keyword = 'kingsholm', start = 27522, vidblain = false, noquest = false, min = 30, max = 65, lock = 0},
    {name = "Kobold Siege Camp", keyword = 'siege', start = 43265, vidblain = false, noquest = false, min = 80, max = 100, lock = 0},
    {name = "Rosewood Castle", keyword = 'rosewood', start = 6901, vidblain = false, noquest = false, min = 60, max = 150, lock = 25}
 }